### ISSUE TITLE
Hiow to log to 2 different accounts

### ISSUE THREAD

**Issue by gomifromparis** [aartek/trikatuka-tool#1]
Hi,

I tried the cloud version to migrate an account to the new  family account. I don't seem to be able to login with 2 different accounts : when authentified by spotify one as "Old user", I can't use another account to log the "New User" . So no migration :-(
Tried on Firefox + Edge. 
Any clue ?

**Comment by aartek** [comment]
Trikatuka in this github project is deprecated. I've made a [new one](https://github.com/aartek/trikatuka2). It is also available online on: http://trikatuka-aknakn.rhcloud.com/#/ and I don't have a problem to login with 2 different accounts there.

![trikatuka](https://cloud.githubusercontent.com/assets/5053151/15723031/d835c16c-2840-11e6-8942-923e8f6f1c4a.jpg)

Are you sure your credentials are correct? 

If it still doesn't work you may check in developer console/network tab if `/socket.io*` request returns http status 200. If not, something may be wrong with socket connection between your browser and server. Then, let me know and I will try to investigate.

**Comment by gomifromparis** [comment]
Yes credentials OK, here's what happens:

click sign in

So OK, but when I click on the "new user" sign in

It says I'm logged as the first user. So I can't add a second 
credential, because probably the spotify authentication cookie is 
already used.

Gomi

**Comment by aartek** [comment]
Ohh, did you read the popup messsage? :) 

![tr](https://cloud.githubusercontent.com/assets/5053151/15744292/6463a2f0-28cb-11e6-9233-c3615cdb516c.png)

You have to click this link in parenthesis to login to another account ;)

**Comment by gomifromparis** [comment]
Yey, thanks, didn't see it was a clickable link !

Sorry for my moronism , and thanks for the tool, gonna do a couple 
transfers with my family account.

Sorry again for the inconvenience.

Gomi
