### ISSUE TITLE
Getting SyntaxError: invalid syntax when running in local

### ISSUE THREAD

**Issue by daniwalter001** [aartek/trikatuka-tool#2]
I saw your website was not responding so I set up your project locally ( python 2 env and web.py, even spotity developper app)
When try to run it, the login works but it failed to get playlist and albums. Im getting SyntaxError: invalid syntax. Hope u can help

**Comment by aartek** [comment]
The site is up again. Btw, I don't support python version, so if you'd like to run it locally please check this repo https://github.com/aartek/trikatuka2

**Comment by daniwalter001** [comment]
Thanks mate
